apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: prometheus-service
  replicas: 1
  template:
    metadata:
      labels:
        run: prometheus-service
    spec:
      containers:
        - name: prometheus-service
          image: imrajdas/prometheus-service:ci
          ports:
            - containerPort: 8080
          env:
            - name: METRICS_SCRAPE_PATH
              value: '/metrics'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: EVENTBROKER
              value: 'http://localhost:8082/event'
            - name: API
              value: 'ws://api-service:8080/websocket'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: keptn-prometheus-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-prometheus-service
  namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
    resourceNames:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn
