apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: bacherfl/prometheus-service
      docker:    # 	beta describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile_dev
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml