kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: keptn_integration
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: keptn_integration
        # Send severity=webhook alerts to the webhook
          match:
            severity: webhook
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: keptn_integration
      webhook_configs:
      - url: http://prometheus-service.keptn.svc.cluster.local:8080
      
